[package]
name = "erl_tokenize"
version = "0.11.0"
description = "Erlang source code tokenizer"
homepage = "https://github.com/sile/erl_tokenize"
repository = "https://github.com/sile/erl_tokenize"
readme = "README.md"
keywords = ["erlang", "tokenizer", "lexer"]
categories = ["parser-implementations"]
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.88"

[dependencies]

[dev-dependencies]
noargs = "0.4.1"
nojson = "0.3.13"
noprop = "0.2.0"
