//! Compare the erl_tokenize output against an `erl_scan` fixture.
//!
//! Reads a JSONL fixture (one JSON object per line, each of the form
//! `{"<path>":[["<kind>","<text>"], ...]}`) generated by
//! `scripts/dump-otp-fixture.escript`, then tokenizes the same source
//! file with `erl_tokenize::scan_token` and asserts a per-token
//! `(kind, text)` match. White-space and comment tokens are absent from
//! the fixture and are skipped on the erl_tokenize side.
//!
//! Usage:
//!
//! ```text
//! cargo run --release --example otp_diff -- <fixture.jsonl>
//! ```
//!
//! `<path>` in the fixture is the absolute path recorded at generation
//! time; the same path must resolve to the same source content when the
//! diff runs (the CI job clones the OTP tree at the same tag, so the
//! paths line up).
//!
//! Exit code is `1` if any mismatch was detected, `0` otherwise.

use std::fs;
use std::path::PathBuf;
use std::process::ExitCode;

fn main() -> Result<ExitCode, Box<dyn std::error::Error>> {
    let mut args = std::env::args().skip(1);
    let fixture_path = args.next().ok_or("usage: otp_diff <fixture.jsonl>")?;
    if args.next().is_some() {
        return Err("usage: otp_diff <fixture.jsonl>".into());
    }

    let fixture = fs::read_to_string(&fixture_path)?;

    let mut files = 0usize;
    let mut ok_files = 0usize;
    let mut mismatch_files = 0usize;
    let mut missing_sources = 0usize;

    for (lineno, line) in fixture.lines().enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        files += 1;
        let (path, expected) = match parse_line(line) {
            Ok(pair) => pair,
            Err(e) => {
                eprintln!("{fixture_path}:{}: parse failure: {e}", lineno + 1);
                mismatch_files += 1;
                continue;
            }
        };
        let source = match fs::read_to_string(&path) {
            Ok(s) => s,
            Err(_) => {
                missing_sources += 1;
                continue;
            }
        };
        match compare_file(&path, &source, &expected) {
            Ok(()) => ok_files += 1,
            Err(msg) => {
                eprintln!("{msg}");
                mismatch_files += 1;
            }
        }
    }

    eprintln!(
        "FILES: {files}, OK: {ok_files}, MISMATCH: {mismatch_files}, MISSING_SOURCE: {missing_sources}"
    );
    Ok(ExitCode::from(u8::from(mismatch_files > 0)))
}

/// Parse one fixture line into a `(source path, expected tokens)` pair.
///
/// Each line is a single-key JSON object; the key is the source path and
/// the value is an array of `[kind, text]` pairs.
fn parse_line(line: &str) -> Result<(PathBuf, Vec<(String, String)>), String> {
    let raw = nojson::RawJson::parse(line).map_err(|e| format!("json parse: {e}"))?;
    let mut object = raw
        .value()
        .to_object()
        .map_err(|e| format!("expected object: {e}"))?;
    let (key, val) = object.next().ok_or("empty object")?;
    if object.next().is_some() {
        return Err("expected single-key object".into());
    }
    let path = key
        .to_unquoted_string_str()
        .map_err(|e| format!("path key: {e}"))?
        .into_owned();
    let mut expected = Vec::new();
    for tok in val
        .to_array()
        .map_err(|e| format!("expected token array: {e}"))?
    {
        expected.push(parse_token_entry(tok)?);
    }
    Ok((PathBuf::from(path), expected))
}

fn parse_token_entry(entry: nojson::RawJsonValue<'_, '_>) -> Result<(String, String), String> {
    let mut items = entry
        .to_array()
        .map_err(|e| format!("token entry not array: {e}"))?;
    let kind = items
        .next()
        .ok_or("token entry missing kind")?
        .to_unquoted_string_str()
        .map_err(|e| format!("kind: {e}"))?
        .into_owned();
    let text = items
        .next()
        .ok_or("token entry missing text")?
        .to_unquoted_string_str()
        .map_err(|e| format!("text: {e}"))?
        .into_owned();
    if items.next().is_some() {
        return Err("token entry has more than two fields".into());
    }
    Ok((kind, text))
}

/// Scan `source` with erl_tokenize, skipping white-space and comment
/// tokens (which are excluded from the fixture), and compare token by
/// token against `expected`.
fn compare_file(
    path: &std::path::Path,
    source: &str,
    expected: &[(String, String)],
) -> Result<(), String> {
    let mut actual = Vec::new();
    let mut pos = erl_tokenize::Position::new();
    loop {
        match erl_tokenize::scan_token(source, pos) {
            Ok(Some(t)) => {
                pos = t.end();
                if !matches!(
                    t.kind(),
                    erl_tokenize::TokenKind::Whitespace | erl_tokenize::TokenKind::Comment
                ) {
                    actual.push(t);
                }
            }
            Ok(None) => break,
            Err(e) => {
                return Err(format!(
                    "{}: scan_token failure at {}: {}",
                    path.display(),
                    pos,
                    e
                ));
            }
        }
    }

    for (i, exp) in expected.iter().enumerate() {
        match actual.get(i) {
            Some(act) => {
                let act_kind = erl_scan_kind_name(&act.kind());
                let act_text = act.text(source);
                if !kinds_match(&exp.0, &act_kind) || act_text != exp.1 {
                    return Err(format!(
                        "{}: token[{}] mismatch: expected ({:?}, {:?}), got ({:?}, {:?})",
                        path.display(),
                        i,
                        exp.0,
                        exp.1,
                        act_kind,
                        act_text,
                    ));
                }
            }
            None => {
                return Err(format!(
                    "{}: token[{}] missing (expected ({:?}, {:?}), got EOF)",
                    path.display(),
                    i,
                    exp.0,
                    exp.1,
                ));
            }
        }
    }
    if actual.len() > expected.len() {
        let t = &actual[expected.len()];
        return Err(format!(
            "{}: extra token at [{}]: ({:?}, {:?})",
            path.display(),
            expected.len(),
            erl_scan_kind_name(&t.kind()),
            t.text(source),
        ));
    }
    Ok(())
}

/// Map an `erl_tokenize::TokenKind` to the erl_scan kind atom string
/// that the fixture records via `atom_to_list/1`.
fn erl_scan_kind_name(kind: &erl_tokenize::TokenKind) -> String {
    match kind {
        erl_tokenize::TokenKind::Atom => "atom".to_owned(),
        erl_tokenize::TokenKind::Char => "char".to_owned(),
        erl_tokenize::TokenKind::Float => "float".to_owned(),
        erl_tokenize::TokenKind::Integer => "integer".to_owned(),
        erl_tokenize::TokenKind::Keyword(k) => k.as_str().to_owned(),
        erl_tokenize::TokenKind::String => "string".to_owned(),
        erl_tokenize::TokenKind::Symbol(s) => match s {
            erl_tokenize::Symbol::Dot => "dot".to_owned(),
            other => other.as_str().to_owned(),
        },
        erl_tokenize::TokenKind::Variable => "var".to_owned(),
        // Fixture emits `sigil_string` for merged sigil_prefix + string +
        // sigil_suffix triples (see scripts/dump-otp-fixture.escript).
        erl_tokenize::TokenKind::SigilString => "sigil_string".to_owned(),
        // The following are excluded from the fixture, but map them for
        // debug output should they ever show up.
        erl_tokenize::TokenKind::Whitespace => "white_space".to_owned(),
        erl_tokenize::TokenKind::Comment => "comment".to_owned(),
    }
}

/// erl_scan uses the atom `dot` for the form-terminating dot (followed
/// by whitespace or EOF) and the atom `'.'` for the dot inside
/// `record.field` / `map.key` accessors. erl_tokenize represents both
/// as `erl_tokenize::Symbol::Dot` and cannot distinguish them from kind alone, so
/// accept either fixture kind for our `dot` mapping.
fn kinds_match(expected: &str, actual: &str) -> bool {
    if expected == actual {
        return true;
    }
    matches!((expected, actual), ("dot", ".") | (".", "dot"))
}

// Silence unused imports on missing kinds during development.
#[allow(dead_code)]
fn _unused(_t: erl_tokenize::Token) {}
